version: '3.5'
services:
  openresty:
    build: ./openresty
    container_name: dev_openresty
    hostname: test
    depends_on:
      - rest-proxy
    ports:
      - "8080:8081"
    volumes:
      - type: bind
        source: ./openresty/nginx.conf
        target: /usr/local/openresty/nginx/conf/nginx.conf
      - type: bind
        source: ./openresty/nginx.conf.d/
        target: /usr/local/openresty/nginx/conf/conf.d/
      - type: bind
        source: ./keystore/combined.key
        target: /certs/combined.crt
      - type: bind
        source: ./keystore/privkey.key
        target: /certs/privkey.key
      - type: bind
        source: ./keystore/certchain.crt
        target: /certs/certchain.crt
      - type: bind
        source: ../
        target: /usr/local/lib/lua/lua-resty-kafka/
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      kafka:

