version: '3.5'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/zookeper_jaas.conf"
    networks:
      kafka:

    volumes:
      - ./zookeper_jaas.conf:/etc/kafka/zookeper_jaas.conf

  add-kafka-users:
    image: confluentinc/cp-kafka:6.2.0
    networks:
      kafka:
    command: >
     /bin/bash -c "
        while ! nc -z broker 9092;
        do
          echo sleeping;
          sleep 1;
        done;
        kafka-configs --bootstrap-server broker:9092 --alter --add-config 'SCRAM-SHA-256 =[iterations=4096,password=client-password]' --entity-type users --entity-name client;
        kafka-configs --bootstrap-server broker:9092 --alter --add-config 'SCRAM-SHA-512 =[iterations=4096,password=client-password]' --entity-type users --entity-name client-sha512;"
    healthcheck:
      test: nc -z broker 9092

  create-delegation-token:
    image: confluentinc/cp-kafka:6.2.0
    networks:
      kafka:
    user: root
    command: >
     /bin/bash -c "
        while ! nc -z broker 9092;
        do
          echo sleeping;
          sleep 1;
        done;
        kafka-delegation-tokens --bootstrap-server broker:29093 --create --max-life-time-period -1 --command-config /etc/kafka/client.config --renewer-principal User:admin | awk '/TOKENID/{getline; print}' | tr ' ' '\n'| head -2 > /etc/kafka/tokens/delegation-tokens.env"
    healthcheck:
      test: nc -z broker 9092
    volumes:
      - ./truststore:/etc/kafka/secrets/truststore
      - ./keystore:/etc/kafka/secrets/keystore
      - ./credentials:/etc/kafka/secrets/
      - ./client.config:/etc/kafka/client.config
      - ./tokens/:/etc/kafka/tokens:Z
      - ./broker-config/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf

  broker:
    image: confluentinc/cp-kafka:6.2.0
    hostname: broker
    depends_on:
      - zookeeper
    healthcheck:
      test: nc -z broker 9092
    ports:
      - "29092:29092"
      - "19093:19093"
      - "9092:9092"
      - "9093:9093"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SSL:SSL,SASL_SSL:SASL_SSL,SASL_PLAINTEXT:SASL_PLAINTEXT
      KAFKA_ADVERTISED_HOST_NAME: broker
      KAFKA_LISTENERS:  SASL_SSL://broker:9093,PLAINTEXT_HOST://broker:9092,PLAINTEXT://broker:29092,SSL://broker:29093,SASL_PLAINTEXT://broker:19093
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://broker:9093,PLAINTEXT_HOST://broker:9092,PLAINTEXT://broker:29092,SSL://broker:29093,SASL_PLAINTEXT://broker:19093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # ssl
      KAFKA_SSL_KEYSTORE_FILENAME: keystore/kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: ssl_key_credentials
      KAFKA_SSL_KEYSTORE_PASSWORD: confluent
      KAFKA_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_SSL_TRUSTSTORE_FILENAME: truststore/kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: ssl_key_credentials
      KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12
      KAFKA_SSL_KEY_PASSWORD: confluent
      KAFKA_SSL_KEY_CREDENTIALS: ssl_key_credentials

      # Enable SASL SSL configuration
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: SASL_PLAIN,PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
      KAFKA_SASL_MECHANISMS: PLAIN,SCRAM-SHA-256,SCRAM-SHA-512

      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: PLAINTEXT

      # KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      # Ignores name resolution
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''

      # 'required' for mTLS
      KAFKA_SSL_CLIENT_AUTH: 'requested'

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

      KAFKA_DELEGATION_TOKEN_MASTER_KEY: 'foo'

      # 'requested' for TLS
      # KAFKA_SSL_CLIENT_AUTH: requested

      # Enables tcp lib level debugging
      KAFKA_OPTS: "-Djavax.net.debug=all -Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
    networks:
      kafka:
    volumes:
      - ./truststore:/etc/kafka/secrets/truststore
      - ./keystore:/etc/kafka/secrets/keystore
      - ./credentials:/etc/kafka/secrets/
      - ./client.config:/etc/kafka/client.config
      - ./broker-config/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf

  broker2:
    image: confluentinc/cp-kafka:6.2.0
    hostname: broker2
    depends_on:
      - zookeeper
    healthcheck:
      test: nc -z broker2 9092
    ports:
      - "29092"
      - "19093"
      - "9092"
      - "9093"
      - "9101"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SSL:SSL,SASL_SSL:SASL_SSL,SASL_PLAINTEXT:SASL_PLAINTEXT
      KAFKA_ADVERTISED_HOST_NAME: broker2
      KAFKA_LISTENERS:  SASL_SSL://broker2:9093,PLAINTEXT_HOST://broker2:9092,PLAINTEXT://broker2:29092,SSL://broker2:29093,SASL_PLAINTEXT://broker2:19093
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://broker2:9093,PLAINTEXT_HOST://broker2:9092,PLAINTEXT://broker2:29092,SSL://broker2:29093,SASL_PLAINTEXT://broker2:19093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # ssl
      KAFKA_SSL_KEYSTORE_FILENAME: keystore/kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: ssl_key_credentials
      KAFKA_SSL_KEYSTORE_PASSWORD: confluent
      KAFKA_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_SSL_TRUSTSTORE_FILENAME: truststore/kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: ssl_key_credentials
      KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12
      KAFKA_SSL_KEY_PASSWORD: confluent
      KAFKA_SSL_KEY_CREDENTIALS: ssl_key_credentials

      # Enable SASL SSL configuration
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: SASL_PLAIN,PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
      KAFKA_SASL_MECHANISMS: PLAIN,SCRAM-SHA-256,SCRAM-SHA-512

      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: PLAINTEXT

      # KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      # Ignores name resolution
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''

      # 'required' for mTLS
      KAFKA_SSL_CLIENT_AUTH: 'requested'

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

      KAFKA_DELEGATION_TOKEN_MASTER_KEY: 'foo'

      # 'requested' for TLS
      # KAFKA_SSL_CLIENT_AUTH: requested

      # Enables tcp lib level debugging
      KAFKA_OPTS: "-Djavax.net.debug=all -Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
    networks:
      kafka:
    volumes:
      - ./truststore:/etc/kafka/secrets/truststore
      - ./keystore:/etc/kafka/secrets/keystore
      - ./credentials:/etc/kafka/secrets/
      - ./client.config:/etc/kafka/client.config
      - ./broker-config/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf

  rest-proxy:
    image: confluentinc/cp-kafka-rest:6.2.0
    depends_on:
      - broker
      - broker2
    ports:
      - 8082:8082
    hostname: rest-proxy
    healthcheck:
      test: ["CMD", "curl" ,"http://0.0.0.0:8082/topics"]
      interval: 10s
      timeout: 10s
      retries: 50
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker:9092,broker2:9092'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
    networks:
      kafka:

  kong:
    image: kong/kong:3.6
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yaml
      KONG_STREAM_LISTEN: "0.0.0.0:9092 reuseport backlog=65536, 0.0.0.0:9093 ssl reuseport backlog=65536"
      KONG_ROUTER_FLAVOR: traditional
    ports:
      - "9092"
      - "9093"
    networks:
      kafka:
        aliases:
          - "fake"
          - "kafkaproxy"
    volumes:
      - ./kong/kong.yaml:/kong/kong.yaml
      
networks:
    kafka:
