name: run
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: set permissions
        run: sudo chown -R $(id -u):$(id -g) dev/tokens
      - name: Setup environment
        run: make devup
      - name: Create delegation tokens
        run: make delegation-token
      - name: Run busted tests
        env:
          CONFLUENT_BOOTSTRAP_SERVER: ${{ secrets.KONG_SPEC_TEST_CONFLUENT_HOST }}
          CONFLUENT_BOOTSTRAP_PORT: ${{ secrets.KONG_SPEC_TEST_CONFLUENT_PORT }}
          CONFLUENT_API_KEY: ${{ secrets.KONG_SPEC_TEST_CONFLUENT_CLUSTER_API_KEY }}
          CONFLUENT_API_SECRET: ${{ secrets.KONG_SPEC_TEST_CONFLUENT_CLUSTER_API_SECRET }}
          CONFLUENT_TOPIC: ${{ secrets.KONG_SPEC_TEST_CONFLUENT_TOPIC }}
          EVENTHUB_CREDENTIALS: ${{ secrets.EVENTHUB_CREDENTIALS }}
          EVENTHUB_HOST: ${{ secrets.EVENTHUB_HOST }}
        run: make test
      - name: Get logs
        if: ${{ failure() }}
        run: make devlogs
